name: planyapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  cloud_firestore: ^2.1.0
  provider: ^5.0.0
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/planyapp.png"

flutter_native_splash:
  color: "#3F51B5"
  image: "assets/planyapp.png"

flutter:
  uses-material-design: true
  assets:
    - assets/planyapp.png